name: Rights and Licenses Directory
author: Drexel MRC
markdown: kramdown
highlighter: rouge
baseurl: /data-sharing-directory
description: Drexel University | MRC
title: Data Sharing Directory
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal