name: Rights and Licenses Directory
author: Drexel MRC
markdown: kramdown
description: Drexel University | MRC
title: Data Sharing Directory
google_analytics: 
theme: jekyll-theme-minimal
twitter_url: https://twitter.com/all_metadata
flickr_url: https://www.flickr.com/photos/10729528@N03/
